[package]
name = "stonedb-server"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
bytes = "1"
uuid = { version = "1.7.0", features = ["v4", "fast-rng"] }
format-bytes = "0.3"
log = { version = "0.4", features = ["kv", "serde"] }
regex = "1"
logos="0.14"
chrono = {version = "0.4.34"}
base64 = {version = "0.22.0"}
tempdir = "0.3.7"
serde-jsonlines = { version = "0.5" }


[dev-dependencies]
cucumber = "0.20.2"
